### ISSUE TITLE
Line 115 of mc-server-installer.sh missing "M" for starting minecraft server.

### ISSUE THREAD

**Issue by koreykaczor** [kz6fittycent/mc-server-installer#2]
java -Xmx16384 -Xms1024M -jar server.jar nogui

Should be:

java -Xmx16384M -Xms1024M -jar server.jar nogui

I've never used github before so apologies in any awkward methodologies for reporting this.

**Comment by kz6fittycent** [comment]
Thanks for catching that! Got it added, new version being built now.
