### ISSUE TITLE
Backup and Migration

### ISSUE THREAD

**Issue by Angelorien** [kz6fittycent/mc-server-installer#6]
Hi there, 

I had a consult about is there is a way to get a backup of my world?

Regards and thank you for you work :D

**Comment by kz6fittycent** [comment]
The files will (all) be in `~/snap/mc-server-installer/current` - I've even imported old `server.properties`, world folder(s), et cetera into that folder and it all just works. Hope this helps.

**Comment by Angelorien** [comment]
HI there. 
Thanks for the quick reply. 

In a backup i had of that folder. and paste the jar file. executed and open a new world. didn't load the previous one. 

i did the same in a windows but had the same issue. 

i tried using "paper-231.jar" and didn't work either. always open a new world. 

(always executing the jar file in the current folder)

Regards :D

**Comment by kz6fittycent** [comment]
Rename your jar to server.jar and try it that way

**Comment by Angelorien** [comment]
Hi there, 
didn't work :(

is there a way to export the world??
or to know in which folder is located ?
Regards

**Comment by kz6fittycent** [comment]
Everything you'd need is in `~/snap/mc-server-installer/current`. In mine, there's a folder that's created by the name of my world and all it's associated files. If you wanted to back it all up, you'd just use the following options:

### Option 1. Tarball it: 

                `tar -cvzf ~/myworld.tar.gz ~/snap/mc-server-installer/current/*`
                 
                 This will create a tarball and place it in your home directory

### Option 2. Just copy it all into a directory in `/home/user`:  

                `mkdir -p ~/myworldbackup`

                `cp -r ~/snap/mc-server-installer/current/* ~/myworldbackup`


### Maybe a future feature?

Your question has actually inspired a potential future feature for the snap - to allow for users to backup their world files into `/home/user`

**Comment by kz6fittycent** [comment]
Never mind, I just did it! You can refresh your snap and it will appear in version 7.2. Hope you enjoy it.
