### ISSUE TITLE
How can I make this run headlessly?

### ISSUE THREAD

**Issue by UxuginPython** [kz6fittycent/mc-server-installer#9]
I want the server to run in the background at boot without having to select which option I want every time. I tried `mc-server-installer -7` but that didn't work. How would I go about doing this? There's no man page and I didn't know where else to ask. I'm running Ubuntu Jammy Jellyfish and Minecraft 1.18.2.

**Comment by kz6fittycent** [comment]
The snap is really meant as an easy method for new folks to "just get it working". 

You can use `screen` to start it up and run it. 

If you want to run minecraft-server as a daemon, I'd recommend following these instructions: https://bobcares.com/blog/install-minecraft-server-on-ubuntu/
